import { Issue } from '@/lib/types/issues'

// Simple issue data that users can easily edit
// Just add title, description, type, and optionally other fields
// The system will auto-generate IDs, dates, and other metadata
export const userIssues = [
  {
    title: 'Code generation fails with complex nested components',
    description: 'When trying to generate components with deeply nested structures, v0 fails to produce valid React code. The generated JSX has incorrect closing tags and missing imports.',
    type: 'bug' as const,
    priority: 'high' as const,
    category: 'api' as const,
    tags: ['code-generation', 'jsx', 'nested-components'],
    author: 'developer123',
    githubIssueUrl: 'https://github.com/vercel/v0-issues/issues/1',
    reproductionSteps: [
      'Create a prompt requesting a complex nested component',
      'Include multiple levels of nesting (3+ levels)',
      'Submit the prompt to v0',
      'Observe the generated code'
    ],
    expectedBehavior: 'Valid React JSX with proper imports and closing tags',
    actualBehavior: 'Invalid JSX with missing closing tags and import statements'
  },
  {
    title: 'Add support for React Server Components',
    description: 'It would be great if v0 could generate React Server Components with proper async/await patterns and server-side data fetching.',
    type: 'feature' as const,
    priority: 'medium' as const,
    category: 'api' as const,
    tags: ['server-components', 'nextjs', 'async'],
    author: 'nextjs_fan',
    githubIssueUrl: 'https://github.com/vercel/v0-issues/issues/2'
  },
  {
    title: 'Improve TypeScript type generation',
    description: 'Generated components often have loose typing. Would be great to have more precise TypeScript interfaces and proper prop types.',
    type: 'enhancement' as const,
    priority: 'medium' as const,
    category: 'api' as const,
    tags: ['typescript', 'types', 'props'],
    author: 'ts_developer',
    githubIssueUrl: 'https://github.com/vercel/v0-issues/issues/3'
  },
  {
    title: 'UI becomes unresponsive with large prompts',
    description: 'When submitting very long prompts (>2000 characters), the v0 interface becomes unresponsive and sometimes crashes.',
    type: 'bug' as const,
    priority: 'high' as const,
    category: 'ui' as const,
    tags: ['performance', 'ui', 'large-prompts'],
    author: 'power_user',
    status: 'closed' as const,
    githubIssueUrl: 'https://github.com/vercel/v0-issues/issues/4'
  },
  {
    title: 'Add dark mode support for generated components',
    description: 'Generated components should automatically include dark mode variants using Tailwind CSS dark: prefix classes.',
    type: 'feature' as const,
    priority: 'low' as const,
    category: 'ui' as const,
    tags: ['dark-mode', 'tailwind', 'theming'],
    author: 'design_lover',
    githubIssueUrl: 'https://github.com/vercel/v0-issues/issues/5'
  },
  {
    title: 'Documentation: Add examples for complex form handling',
    description: 'The current documentation lacks comprehensive examples for handling complex forms with validation, file uploads, and multi-step workflows.',
    type: 'documentation' as const,
    priority: 'medium' as const,
    category: 'documentation' as const,
    tags: ['forms', 'validation', 'examples', 'tutorial'],
    author: 'doc_contributor',
    githubIssueUrl: 'https://github.com/vercel/v0-issues/issues/6'
  },
  {
    title: 'Add support for Framer Motion animations',
    description: 'It would be helpful if v0 could generate components with Framer Motion animations for common UI patterns like page transitions, hover effects, and loading states.',
    type: 'feature' as const,
    priority: 'low' as const,
    category: 'ui' as const,
    tags: ['animations', 'framer-motion', 'transitions'],
    author: 'animation_dev',
    githubIssueUrl: 'https://github.com/vercel/v0-issues/issues/7'
  },
  {
    title: 'Generated forms lack proper accessibility attributes',
    description: 'Forms generated by v0 are missing important accessibility features like proper ARIA labels, focus management, and screen reader support.',
    type: 'bug' as const,
    priority: 'high' as const,
    category: 'ui' as const,
    tags: ['accessibility', 'forms', 'aria', 'a11y'],
    author: 'a11y_advocate',
    githubIssueUrl: 'https://github.com/vercel/v0-issues/issues/8',
    reproductionSteps: [
      'Generate a form component with multiple input fields',
      'Test with a screen reader',
      'Check for proper ARIA labels and descriptions',
      'Verify keyboard navigation works correctly'
    ],
    expectedBehavior: 'Forms should have proper ARIA labels, descriptions, and keyboard navigation',
    actualBehavior: 'Generated forms lack accessibility attributes and proper focus management'
  }
]

// Helper type for user input (what users need to provide)
export type UserIssueInput = {
  title: string
  description: string
  type: 'bug' | 'feature' | 'enhancement' | 'documentation' | 'question'
  priority?: 'low' | 'medium' | 'high' | 'critical'
  category?: 'ui' | 'performance' | 'api' | 'documentation' | 'integration' | 'other'
  tags?: string[]
  author?: string
  status?: 'open' | 'in-progress' | 'closed' | 'duplicate' | 'wont-fix'
  assignee?: string
  githubIssueUrl?: string
  githubPrUrl?: string
  reproductionSteps?: string[]
  expectedBehavior?: string
  actualBehavior?: string
  environment?: {
    browser?: string
    os?: string
    v0Version?: string
    nodeVersion?: string
    additionalInfo?: string
  }
}
